#!/bin/bash
# inject-domain-map.sh — UserPromptSubmit hook
#
# When the user invokes /plan, /domain-map, or /get-context, inject a compact
# model graph extracted from tmp/architecture/models-erd.dot as additional
# context. Pointer-references to the on-disk artefacts let Claude drill in via
# the domain-map skill rather than reading the raw 16MB+ dot files.
#
# Tuned for payaus, but project-agnostic — silently no-ops in any cwd that
# doesn't have tmp/architecture/models-erd.dot or can't regenerate it.
# Regenerates artefacts via `bundle exec rake architecture_map:generate` only
# when any are missing; the user-prompt-submit event timeout is set high
# enough in settings.json to accommodate the cold-cache regen path.

INPUT=$(cat)
PROMPT=$(echo "$INPUT" | jq -r '.prompt // empty')
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

# Trigger on slash-command tag (`/plan` from Claude Code's plan-mode entry,
# or `/domain-map` / `/get-context` skill invocations). Also catch the bare
# command form at the start of the prompt as a fallback.
echo "$PROMPT" | grep -qE '<command-name>/(plan|domain-map|get-context)</command-name>|^/(plan|domain-map|get-context)(\s|$)' || exit 0

# Use cwd from the hook input when available — works across worktrees, which
# don't live at the main repo's path. Fall back to $PWD for older harness
# versions.
[ -n "$CWD" ] && cd "$CWD" 2>/dev/null

MODELS_DOT="tmp/architecture/models-erd.dot"
CONTROLLERS_DOT="tmp/architecture/controllers.dot"
COMPOSITIONS_DOT="tmp/architecture/compositions.dot"

# Regenerate only if any artefact is missing — rails-erd boot is expensive.
# Silent on failure: if there's no `architecture_map:generate` rake task in
# this project, the hook just no-ops.
if [ ! -f "$MODELS_DOT" ] || [ ! -f "$CONTROLLERS_DOT" ] || [ ! -f "$COMPOSITIONS_DOT" ]; then
  bundle exec rake architecture_map:generate > /dev/null 2>&1 || exit 0
fi

[ -f "$MODELS_DOT" ] || exit 0

# Parse models-erd.dot into three compact markdown sections:
#   - has_many/has_one edges (solid arrows)
#   - polymorphic/through edges (dotted, constraint=false)
#   - STI hierarchies (arrowtail=onormal), grouped by parent
#
# Filter list mirrors .claude/skills/domain-map/scripts/query.rb INFRA_PREFIXES
# in payaus. Harmless in other projects (those namespaces just won't be
# present).
ERD=$(ruby -e '
  INFRA_PREFIXES = [
    "VersionClasses::",
    "PaperTrail::",
    "ActiveStorage::",
    "ActionText::",
    "ActionMailbox::",
    "Noticed::",
    "Platform::Value::",
  ].freeze

  def infra?(name)
    return true if name == "ApplicationRecord"
    INFRA_PREFIXES.any? { |p| name.start_with?(p) }
  end

  s = STDIN.read
  s.gsub!(/label = <\{.*?<font[^>]+point-size="11">([^<]+)<\/font>.*?\}>/m) { %Q(label="#{$1}") }

  nodes = []
  has_many = []
  polymorphic = []
  sti = Hash.new { |h, k| h[k] = [] }

  s.each_line do |line|
    if m = line.match(/"?m_(?<a>[\w:]+)"?\s*->\s*"?m_(?<b>[\w:]+)"?\s*\[(?<attrs>[^\]]*)\]/)
      a, b, attrs = m[:a], m[:b], m[:attrs]
      next if infra?(a) || infra?(b)
      if attrs.include?(%q(constraint = "false"))
        polymorphic << [a, b]
      elsif attrs.include?(%q(arrowtail = "onormal"))
        sti[a] << b
      else
        has_many << [a, b]
      end
    elsif m = line.match(/"?m_[\w:]+"?\s*\[.*label="([^"]+)"/)
      name = m[1]
      nodes << name unless infra?(name)
    end
  end

  out = []
  out << "### Models\n"
  out << nodes.uniq.sort.join(", ") + "\n"
  out << "\n### has_many / has_one  (A -> B means A has_many/has_one B; B belongs_to A)\n"
  has_many.sort.uniq.each { |a, b| out << "#{a} -> #{b}\n" }
  unless polymorphic.empty?
    out << "\n### Polymorphic / through  (-.->)\n"
    polymorphic.sort.uniq.each { |a, b| out << "#{a} -.-> #{b}\n" }
  end
  unless sti.empty?
    out << "\n### STI / inheritance  (parent ==> children)\n"
    sti.sort.each { |parent, children| out << "#{parent} ==> #{children.sort.uniq.join(", ")}\n" }
  end
  print out.join
' < "$MODELS_DOT") || exit 0

[ -z "$ERD" ] && exit 0

# Cap injection at ~10KB. Truncate the models list if needed; on-disk
# artefacts remain queryable via the domain-map skill regardless.
if [ "$(echo -n "$ERD" | wc -c)" -gt 10000 ]; then
  ERD=$(echo "$ERD" | head -c 10000)
  ERD="${ERD}

…truncated. Query the full graph via the domain-map skill."
fi

jq -n --arg erd "$ERD" '{
  hookSpecificOutput: {
    hookEventName: "UserPromptSubmit",
    additionalContext: (
      "# Domain context — AUTHORITATIVE for this turn. Read before exploring.\n\n" +
      "Extracted from `tmp/architecture/models-erd.dot` (generated by `bundle exec rake architecture_map:generate`). Rails infrastructure noise (PaperTrail, ActiveStorage, ActionText, ActionMailbox, Noticed, Platform::Value, VersionClasses) is filtered; only app domain remains.\n\n" +
      "**Use this as the primary source for domain shape.** Before Grep/Glob/Read over `app/models/**`, consult this block — it already answers \"where does X live\" and \"what associates with Y\". Drop to file reads only for behavioural detail (validations, callbacks, scopes, instance methods).\n\n" +
      "If this looks stale relative to recent code, run `bundle exec rake architecture_map:generate`.\n\n" +
      "## Model graph\n" + $erd + "\n\n" +
      "## On-disk artefacts (query via the domain-map skill — do not Read directly)\n" +
      "- `tmp/architecture/models-erd.dot` — full rails-erd source (AR associations).\n" +
      "- `tmp/architecture/controllers.dot` — controller inheritance hierarchy (railroady).\n" +
      "- `tmp/architecture/compositions.dot` — non-AR POROs/wrappers attached via `.new(self)` at AR call sites. **Rails-erd does not capture these.** When asking \"where does this method live?\", check compositions before deciding the root model is the right home.\n\n" +
      "Drill in with `ruby .claude/skills/domain-map/scripts/query.rb <command> <args>` — see the domain-map skill for the full command list."
    )
  }
}'
exit 0
